services:
  # Static site for the client
  - type: web
    name: client
    env: static
    staticPublishPath: ./dist/client
    routes:
      - path: /*
        dest: /index.html
    build_command: npm run build

  # Web service for the server
  - type: web
    name: server
    env: node
    plan: free
    health_check_path: /api/health
    build_command: npm run build
    start_command: npm start
    env_vars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: your-db-name # Replace with your actual database name on Render
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
